# Generated by Django 4.1.4 on 2022-12-08 03:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221202_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgaccount',
            name='cur_ddt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orgaccount',
            name='max_ddt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orgaccount',
            name='min_ddt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
