# Generated by Django 4.2.1 on 2023-05-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_cluster_org_num_node_req_pending_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgaccount',
            name='email',
            field=models.EmailField(default='support@mail.slideruleearth.io', max_length=254),
        ),
    ]
