# Generated by Django 4.2.1 on 2023-05-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_orgaccount_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgaccount',
            name='cur_nodes',
        ),
        migrations.AddField(
            model_name='cluster',
            name='cur_max_node_cap',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='cur_min_node_cap',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='cur_nodes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cluster',
            name='cur_version',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True),
        ),
    ]
