# Generated by Django 4.2.1 on 2023-05-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_orgaccount_cur_nodes_cluster_cur_max_node_cap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
