# Generated by Django 4.2.1 on 2023-05-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_cluster_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgnumnode',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
