# Generated by Django 4.2.1 on 2023-05-08 16:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_orgnumnode_expiration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsCmdResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ps_cmd_output', models.TextField(default='', help_text='Output from the provisioning system server', verbose_name='Provision Cmd Results')),
                ('error', models.TextField(default='', help_text='Errors/Warnings processing cmd', verbose_name='Provision Server Errors')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('ps_cmd_summary_label', models.TextField(default='', help_text='ps cmd task output', verbose_name='Provision Cmd Task')),
                ('expiration', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_org_cr', to='users.orgaccount')),
            ],
        ),
        migrations.RemoveField(
            model_name='orgnumnode',
            name='show_expire_tm',
        ),
        migrations.DeleteModel(
            name='PsCmdQueueResult',
        ),
    ]
