# Generated by Django 4.2.1 on 2023-05-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_pscmdresult_remove_orgnumnode_show_expire_tm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgaccount',
            name='expire_time',
        ),
        migrations.AddField(
            model_name='cluster',
            name='expire_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
