# Generated by Django 4.2.1 on 2023-05-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_orgaccount_expire_time_cluster_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pscmdresult',
            name='ps_cmd_summary_label',
            field=models.TextField(default='', help_text='ps cmd task output', verbose_name='Provision Cmd'),
        ),
    ]
