# Generated by Django 4.2.1 on 2023-05-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_pscmdresult_ps_cmd_summary_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pscmdresult',
            name='ps_cmd_output',
            field=models.TextField(default='', editable=False, help_text='Output from the provisioning system server', verbose_name='Provision Cmd Results'),
        ),
        migrations.AlterField(
            model_name='pscmdresult',
            name='ps_cmd_summary_label',
            field=models.TextField(default='', editable=False, help_text='ps cmd task output', verbose_name='Provision Cmd'),
        ),
    ]
