# Generated by Django 4.2.2 on 2023-06-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_cluster_cur_nodes_alter_cluster_org_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='provision_env_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orgaccount',
            name='provisioning_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
