# Generated by Django 4.2.2 on 2023-06-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_cluster_provision_env_ready_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='cnnro_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='cqro_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
