# Generated by Django 4.1.3 on 2022-12-02 21:42

from django.db import migrations


def populate_gran_choice(apps, schema_editor):
    GranChoice = apps.get_model('users', 'GranChoice')
    h = GranChoice.objects.create(granularity='HOURLY')
    h.save()
    d = GranChoice.objects.create(granularity='DAILY')
    d.save()
    m = GranChoice.objects.create(granularity='MONTHLY')
    m.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_gran_choice)
    ]