# Generated by Django 4.1.4 on 2022-12-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_orgaccount_cur_ddt_alter_orgaccount_max_ddt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgaccount',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
