# Generated by Django 4.1.6 on 2023-02-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_orgaccount_pcqr_display_age_in_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='orgaccount',
            name='fytd_accrued_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='orgnumnode',
            name='show_expire_tm',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pscmdqueueresult',
            name='show_expire_tm',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orgaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='orgaccount',
            name='max_allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='orgaccount',
            name='monthly_allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
