# Generated by Django 4.2.1 on 2023-05-03 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_orgaccount_admin_max_node_cap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='org_num_node_req_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orgaccount',
            name='loop_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orgaccount',
            name='num_onn',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orgaccount',
            name='num_owner_ps_cmd',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orgaccount',
            name='num_ps_cmd',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orgaccount',
            name='num_ps_cmd_successful',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pscmdqueueresult',
            name='expiration',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.CreateModel(
            name='OwnerPSCmd',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ps_cmd', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('deploy_values', models.JSONField(blank=True, default=dict, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('org', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_org_opscmd', to='users.orgaccount')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_user_opscmd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
