# Generated by Django 4.2.1 on 2023-05-19 13:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_pscmdresult_ps_cmd_output_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='cur_nodes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='org',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.orgaccount'),
        ),
        migrations.AlterField(
            model_name='ownerpscmd',
            name='ps_cmd',
            field=models.CharField(blank=True, default='', editable=False, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='pscmdresult',
            name='error',
            field=models.TextField(default='', editable=False, help_text='Errors/Warnings processing cmd', verbose_name='Provision Server Errors'),
        ),
        migrations.AlterField(
            model_name='pscmdresult',
            name='expiration',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='pscmdresult',
            name='org',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_org_cr', to='users.orgaccount'),
        ),
    ]
