# Generated by Django 4.2.3 on 2023-07-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_orgaccount_num_setup_cmd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='cur_max_node_cap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='cur_min_node_cap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='cur_version',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
