# Generated by Django 4.2.4 on 2023-08-14 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_cluster_cnnro_id_cluster_cnnro_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='cqro_id',
        ),
    ]
