# Generated by Django 4.2.4 on 2023-08-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_cluster_cqro_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='org_num_node_req_pending',
        ),
    ]
