# Generated by Django 4.2.14 on 2024-07-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_cluster_org_num_node_req_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgaccount',
            name='spot_allocation_strategy',
            field=models.CharField(default='lowest-price', max_length=32),
        ),
        migrations.AddField(
            model_name='orgaccount',
            name='spot_max_price',
            field=models.FloatField(default=0.17),
        ),
    ]
