# Generated by Django 4.2.14 on 2024-07-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_orgaccount_spot_allocation_strategy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgaccount',
            name='asg_cfg',
            field=models.CharField(default='unselected', max_length=32),
        ),
    ]
