# Generated by Django 4.2.20 on 2025-03-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_orgaccount_asg_cfg'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgaccount',
            name='availability_zone',
            field=models.CharField(default='us-west-2c', max_length=32),
        ),
    ]
