services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - S3_TEST_FILES=/tmp/prov-sys/test_misc/cluster_tf_versions
      - PS_TEST_DIR=${PS_TEST_DIR:?PS_TEST_DIR is not defined?!}

    volumes:
      - "./test_misc/cluster_tf_versions:/tmp/prov-sys/test_misc/cluster_tf_versions"
      - "./init_aws_localstack.py:/etc/localstack/init/ready.d/init-aws.sh"  # ready hook
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  ps-server:
    ports:
      - 50051:50051
    image: ${DOCKER_REPO}/sliderule-ps-server:${PS_SERVER_DOCKER_TAG}
    container_name: ps-server
    depends_on:
      - localstack
    # volumes:
    #   - ~/.aws/:/root/.aws/
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_SESSION_TOKEN=test
      - AWS_DEFAULT_REGION=us-west-2
      - AWS_EC2_ENDPOINT_URL=http://localstack:4566
      - AWS_S3_ENDPOINT_URL=http://localstack:4566
      - AWS_CE_ENDPOINT_URL=http://localstack:4566
      - TERRAFORM_CLI=tflocal
      - DOMAIN=localhost
      - S3_FILES=/ps_server/test_misc/cluster_tf_versions
      - DOCKER_REPO=icesat2sliderule
      - PS_SERVER_DOCKER_TAG=dev
