# Generated by Django 3.2.12 on 2022-03-18 17:46

from django.db import migrations

# This file gets copied into the 0002_auto<DATE> generated file when the DB is initialized and 
# the 001_initial.py migration file is created

def populate_gran_choices(apps, schema_editor):
    GranChoice = apps.get_model('users', 'GranChoice')
    h = GranChoice.objects.create(granularity='HOURLY')
    h.save()
    d = GranChoice.objects.create(granularity='DAILY')
    d.save()
    m = GranChoice.objects.create(granularity='MONTHLY')
    m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_gran_choices)
    ]
