
    #
    #
    # This file was created by test_misc/replace_terraform_aws_provider.py
    #
    # DO NOT EDIT THIS FILE!
    #
    locals {
        terraform-git-repo = "localstack-testing"
    }
    provider "aws" {
        access_key                  = "test"
        secret_key                  = "test"
        region                      = "us-west-2"
        skip_credentials_validation = true
        skip_metadata_api_check     = true
        skip_requesting_account_id  = true
        s3_use_path_style           = true

        endpoints {
            s3              = "http://localhost:4566"
            sts             = "http://localhost:4566"
            secretsmanager  = "http://localhost:4566"
            route53         = "http://localhost:4566"
            ec2             = "http://localhost:4566"
        } 
    }
    resource "aws_s3_bucket" "test_bucket" {
        bucket = "sliderule"
    }
    